// Echte Themen-Taxonomie des Kiel Instituts für Publikationen (Facette
// "topic" der Publikations-Suche auf kielinstitut.de/de/suche/ -
// unterscheidet sich von den 8 groben Themen-Kacheln auf /de/themen/, die
// für die ganze Website statt speziell für Publikationen gelten).
export const PUBLICATION_TOPICS: string[] = [
  "Deutschland",
  "Internationaler Handel",
  "Wirtschafts- & Finanzkrisen",
  "Europa",
  "Gesundheit",
  "Europäische Union & Euro",
  "China",
  "Globalisierung",
  "Schwellen-& Entwicklungsländer",
  "Arbeitsmarkt",
  "Klima",
  "Fiskalpolitik & Haushalt",
  "Konjunktur",
  "USA",
  "Wachstum",
  "Geldpolitik",
  "Innovation und Strukturwandel",
  "Unternehmen",
  "Afrika",
  "Direktinvestitionen",
  "Asien",
  "Internationale Finanzen",
  "Natürliche Ressourcen",
  "Migration",
  "Finanzmärkte",
  "Nachhaltige Entwicklung",
  "Steuerpolitik",
  "Wohlfahrtsstaat",
  "Amerika",
  "Wirtschaftspolitik in Deutschland",
  "Russland",
  "Verhaltensökonomie",
  "Digitalisierung",
  "Geoökonomie",
  "Krieg",
  "Chancengleichheit",
  "Ukraine",
  "Immobilienmarkt",
  "Zölle",
  "Politische Ökonomie",
  "Industriepolitik",
];
